### ISSUE TITLE
docker compose ?

### ISSUE THREAD

**Issue by EvgenPavlyuchek** [rluisr/mysqlrouter_exporter#57]
how should look docker compose ?
```

  mysql-router:
    image: container-registry.oracle.com/mysql/community-router:8.0.36
    hostname: "mysql-router{{.Task.Slot}}"
    environment:
      MYSQL_HOST: mysql1
      MYSQL_PORT: 3306
      MYSQL_USER: ${DB_ROOT_USER}
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_INNODB_CLUSTER_MEMBERS: 2
      MYSQL_ROUTER_BOOTSTRAP_EXTRA_OPTIONS: --conf-set-option=DEFAULT.max_connections=2048 --conf-set-option=DEFAULT.max_total_connections=2048

  mysqlrouter-exporter:
    image: ghcr.io/rluisr/mysqlrouter_exporter:v5.0.0
    hostname: "mysqlrouter-exporter{{.Task.Slot}}"
    command: --service-name=mysql-router --skip-tls-verify
    environment:
      MYSQLROUTER_EXPORTER_URL: https://mysql-router{{.Task.Slot}}:8443
```
      
1 error
the required flag `--service-name' was not specified
added --service-name=mysql-router
(wasn't mentioned that MYSQLROUTER_EXPORTER_SERVICE_NAME is mandatory in readme)

2 error
failed to create mysql router client. err: Get "https://mysql-router1:8443/api/20190715/swagger.json": tls: failed to verify certificate: x509: certificate is not valid for any names, but wanted to match mysql-router1
added --skip-tls-verify

3 error
Start exporter on 0.0.0.0:49152/metrics
[mysqlrouter_exporter ERROR] response status code is not 200 got 401

what does it want ?
curl -s -k https://mysql-router1:8443/api/20190715/swagger.json works
could be issue with too new version 8.0.36 ?
